# Generated by Django 5.0.6 on 2024-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
